kind: Service
apiVersion: v1
metadata:
  name: java-jmx-svc
spec:
  selector:
    app: java-jmx
  type: NodePort
  ports:
  - name: tcp
    port: 80
    targetPort: 8080
    nodePort: 30080
  - name: jmx
    port: 9090
    targetPort: 9090
    nodePort: 30081
  - name: exporter-port
    port: 9092
    nodePort: 30082